vscode:
  extensions:
    - vscjava.vscode-maven@0.21.2:tFEkt2FqLujaNTLU5AmRiQ==
    - vscjava.vscode-java-test@0.26.1:zSFvujaSnRmpeuPnoTcTAA==
    - redhat.vscode-microprofile@0.1.1:g4Dw46uK0mvhlbXlKtwi6w==
    - zerodind.familiar-java-themes@0.1.2:7hVH+PHrnWD10wQHuctnAg==
    - shrey150.javafx-support@0.0.1:eaqGz85OeSPehfxw7wEZSg==